### ISSUE TITLE
How to use cert-sync with Cert-manager created secrets?

### ISSUE THREAD

**Issue by mtsr** [dunjut/cert-sync#1]
Thanks for your work on this!

Unfortunately, at the moment, it seems like we can't use this with Cert-manager, since there's no way to have it automatically set the certsync.istio.io/autosync annotation.

Do you see any quick solutions that don't involve manual intervention with each Cert-manager generated Secret?

**Comment by dastanza** [comment]
Secrets created by cert-manager have annotations with prefix 'certmanager.k8s.io', which could be used for recognition. 

We could also add a flag (say `--sync-cert-manager-secrets`) to optionally enable or disable this behavior.

**Comment by mtsr** [comment]
The flag sounds like a good solution. Or if you want to make it more generic, allow specifying an annotation to look for instead.

**Comment by dastanza** [comment]
Allowing specifying an annotation (or annotations later) is good idea! Do you want to work on this if that's urgent to you?

**Comment by mtsr** [comment]
Right now I'm still working on the rest of the platform I'm building as a demo. When I need to actually deal with multiple Certificates, I can take a look at it.

**Comment by dastanza** [comment]
I'll do it then. :P

**Comment by dastanza** [comment]
Now I've added two command line flags: `--annotationKey` and `--annotationValue`. Both are optional, defaults to 'certsync.istio.io/autosync' and 'true' respectively.

You could pull image `dunjut/cert-sync:0.2.0` and test it out. :D

**Comment by mtsr** [comment]
Cool, thanks.

As I've just thrown away the entire cluster to do a clean install along the lines I've worked out now, it'll take a bit ;).

**Comment by dastanza** [comment]
Hope it helps!

**Comment by mtsr** [comment]
Yeah. Tested and works beautifully. Nice solution to the istio gateway cert problem.

**Comment by silvam11** [comment]
Hello, I am trying to use cert-sync to "load" some certificates generated by cert-manager but apparently it does not work for me. How can I debug it?

I was testing it and apparently cert-manager renews the certificate but somehow cert-sync does not "reload" it. For instance, as test I killed the ingressgateway pod and I can see that the new certificate.

When I look at the logs I see:

W1022 20:36:04.183067       1 client_config.go:529] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1022 20:36:04.186109       1 sync.go:33] starting cert-sync agent...
I1022 20:36:04.286878       1 sync.go:72] synchronize istio-system/istio-ingressgateway-awx-certs succeeded.
I1022 20:36:04.286987       1 sync.go:72] synchronize istio-system/istio-ingressgateway-logging-certs succeeded.
I1022 20:36:04.287062       1 sync.go:72] synchronize istio-system/istio-ingressgateway-sms-certs succeeded.

Is there any way to increase the logging messages?

**Comment by mtsr** [comment]
That looks like it works. Now you need to reference those certificates from your gateway.

**Comment by mtsr** [comment]
I misread your question.

**Comment by silvam11** [comment]
@mtsr Does the gateway have to be on istio namespace? in my case I have the gateway in a different ns.

**Comment by mtsr** [comment]
Nope, works in the application namespace too.

Does the initial certificate (before renewal) work for you?

**Comment by silvam11** [comment]
Yes. I can access kibana and see on my browser the certificate and the expiration date of 1 hour.

After 1 hour, I checked again and saw that the certificate was not renewed. However, if I delete the ingressgateway pod, I see that the certificate was renewed. Therefore, my understanding is that the certificate was renewed but it was not reloaded by cert-sync. Does it make sense?

**Comment by mtsr** [comment]
Can you check whether the certificate in the volume did get renewed? (by for example `kubectl -n istio-system exec -it istio-ingress-gateway -c cert-sync bash`)

I'm thinking the problem is either cert-sync not picking it up (although a quick look at the code suggests it should work) or istio-proxy not picking it up.

**Comment by silvam11** [comment]
Looking at the volume inside cert-sync container I can see that the crt files seem to be update every minute. For instance:

-rw-r--r--. 1 root root 2829 Oct 22 21:30 istio-ingressgateway-logging-certs.crt
-rw-r--r--. 1 root root 2813 Oct 22 21:30 istio-ingressgateway-awx-certs.crt
-rw-r--r--. 1 root root 2817 Oct 22 21:30 istio-ingressgateway-sms-certs.crt

Only the crt files are updated, the private key files remain with the creation date. Is it normal? I mean, every minute the timestamp changes.

**Comment by mtsr** [comment]
Well, I expect cert-sync to log everytime it does work (see https://github.com/dunjut/cert-sync/blob/3fb797e0ee13f2fc96201ec1929db8e4fd3b3519/pkg/agent/sync.go#L72). So maybe there's another reason for it, if you're not seeing the logs every minute.

And the contents of the crt files? Do they reflect the renewed certificate?

**Comment by silvam11** [comment]
Looking at the cert-sync container logs, I can see the synchronize message every second:

I1022 22:10:41.378949       1 sync.go:72] synchronize istio-system/istio-ingressgateway-logging-certs succeeded.
I1022 22:10:42.009949       1 sync.go:72] synchronize istio-system/istio-ingressgateway-awx-certs succeeded.
I1022 22:10:43.340222       1 sync.go:72] synchronize istio-system/istio-ingressgateway-sms-certs succeeded.
I1022 22:10:43.449594       1 sync.go:72] synchronize istio-system/istio-ingressgateway-logging-certs succeeded.
I1022 22:10:44.085768       1 sync.go:72] synchronize istio-system/istio-ingressgateway-awx-certs succeeded.
I1022 22:10:45.434088       1 sync.go:72] synchronize istio-system/istio-ingressgateway-sms-certs succeeded.
I1022 22:10:45.524103       1 sync.go:72] synchronize istio-system/istio-ingressgateway-logging-certs succeeded.
I1022 22:10:46.167341       1 sync.go:72] synchronize istio-system/istio-ingressgateway-awx-certs succeeded.

Also, looking at the certificate files, I can see that they are changing constantly. Could you explain how the reload works? I mean, when and how cert-sync will reload the new certificates to make them available to be used?

On the gateway configuration, must I use the path mounted by cert-sync? Looking at the gateway, I am using the "normal path" (mounted by the ingressgateway).

**Comment by dastanza** [comment]
@silvam11 

> Could you explain how the reload works? I mean, when and how cert-sync will reload the new certificates to make them available to be used?

If tls secret **key** or **crt** data changes, or cert-sync annotation changes, cert-sync will ensure that the private key and certificate is update to date. The ensure operation is reading the existed file and comparing its bytes with new value, if not equal, overwrite it.

> On the gateway configuration, must I use the path mounted by cert-sync? 

I think you should use the path mounted in ingressgateway, because that's the view envoy sees them.

**Comment by silvam11** [comment]
Hello @mtsr and @dunjut, first of all thanks for your help!

Looking at my problem today, one possible reason of the issue is that the cert-manager is renewing the certificate every second. Therefore, I think it creates an issue for cert-sync. 

My test was to use a TTL of 1 hour to be able to see the renew/reload happening.  Even though you are not from cert-manager, have you seen this behaviour? How did you test it using cert-manager?

**Comment by mtsr** [comment]
Ahhh. Cert-manager has a window before the expiration that it will renew the certificate in. If that’s longer than your TTL of 1 hour it will continuously renew. 

You might be able to configure that, look at cert manager docs.

**Comment by silvam11** [comment]
I sorted out this issue in the sense that the certificate is being renewed every 2 hours (for now) and using openssl command I can see that the certificate file expiration date is correct. Cert-sync seems to sync correctly now. However, when I try to access the application from my browser, I still see the other certificate.

In order to see the new certificate, I need to restart the istio-ingressgateway. Is it the expected behaviour?

**Comment by dastanza** [comment]
@silvam11 Glad to see cert-sync works for you. Honestly speaking, I'm not sure there is a way to make envoy reload new certificates without restarting. I believe it loads them at first use and then keep them in memory.

However, envoy does provides a (new) way to dynamically updating certificates, named SDS (Secret Discovery Service). SDS support is still in progress of istio. So yeah, this is currently an expected behavior.
